name: marocsie
description: "A marocsie delivery app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  flutter_native_splash: ^2.4.4
  dio: ^5.8.0+1
  dropdown_search: ^6.0.2
  mime_type: ^1.0.1
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  file_picker: ^8.3.5
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  awesome_notifications: ^0.10.1
  firebase_messaging: ^15.2.4
  mobile_scanner: ^6.0.9
  pinput: ^5.0.1
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  package_info_plus: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/

flutter_native_splash:
  color: "#ffffff"  # Background color (hex or material color)
  image: assets/images/splash_logo.png  # Path to your logo (optional)
  android_12:
    image: assets/images/splash_logo.png 
    icon_background_color: "#ffffff"
    